#!/usr/bin/env python3
"""
medsyn/utils/merge_synth_with_original.py

Utility script to merge synthetic images (generated by ccDDPM) with original dataset.

The script combines NPZ files containing:
- Original dataset: {split}_images, {split}_labels, {split}_is_synth (all False)
- Synthetic dataset: {split}_images, {split}_labels, {split}_is_synth (all True)

Output format maintains the same structure with both real and synthetic samples.

Author: M.Pascual-González
Date: 2024
"""
from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Optional

import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s - %(name)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def merge_split(
    original_data: dict[str, np.ndarray],
    synth_data: dict[str, np.ndarray],
    split_name: str,
) -> dict[str, np.ndarray]:
    """
    Merge original and synthetic data for a single split.

    Args:
        original_data: Dictionary from original NPZ file
        synth_data: Dictionary from synthetic NPZ file
        split_name: Name of the split (train, val, test)

    Returns:
        Dictionary with merged data for this split

    Raises:
        KeyError: If required keys are missing
        ValueError: If array shapes are incompatible
    """
    logger.info(f"Merging {split_name} split...")

    # Keys for this split
    images_key = f"{split_name}_images"
    labels_key = f"{split_name}_labels"
    is_synth_key = f"{split_name}_is_synth"

    # Check if split exists in both datasets
    if images_key not in original_data:
        logger.warning(f"Split '{split_name}' not found in original dataset, skipping...")
        return {}

    if images_key not in synth_data:
        logger.warning(f"Split '{split_name}' not found in synthetic dataset, skipping...")
        return {}

    # Load original data
    orig_images = original_data[images_key]
    orig_labels = original_data[labels_key]
    orig_is_synth = original_data.get(is_synth_key, np.zeros(len(orig_images), dtype=bool))

    # Load synthetic data
    synth_images = synth_data[images_key]
    synth_labels = synth_data[labels_key]
    synth_is_synth = synth_data.get(is_synth_key, np.ones(len(synth_images), dtype=bool))

    # Validate shapes
    if orig_images.shape[1:] != synth_images.shape[1:]:
        raise ValueError(
            f"Image shape mismatch for {split_name}: "
            f"original {orig_images.shape[1:]} vs synthetic {synth_images.shape[1:]}"
        )

    logger.info(f"  Original: {len(orig_images)} samples (is_synth: {orig_is_synth.sum()} True)")
    logger.info(f"  Synthetic: {len(synth_images)} samples (is_synth: {synth_is_synth.sum()} True)")

    # Concatenate arrays
    merged_images = np.concatenate([orig_images, synth_images], axis=0)
    merged_labels = np.concatenate([orig_labels, synth_labels], axis=0)
    merged_is_synth = np.concatenate([orig_is_synth, synth_is_synth], axis=0)

    logger.info(f"  Merged: {len(merged_images)} samples total")
    logger.info(f"    Real: {(~merged_is_synth).sum()} samples")
    logger.info(f"    Synthetic: {merged_is_synth.sum()} samples")

    # Verify data types
    if merged_images.dtype != np.uint8:
        logger.warning(f"Converting images from {merged_images.dtype} to uint8")
        merged_images = merged_images.astype(np.uint8)

    if merged_labels.dtype != np.int64:
        logger.warning(f"Converting labels from {merged_labels.dtype} to int64")
        merged_labels = merged_labels.astype(np.int64)

    return {
        images_key: merged_images,
        labels_key: merged_labels,
        is_synth_key: merged_is_synth,
    }


def merge_npz_files(
    original_npz_path: Path,
    synth_npz_path: Path,
    output_npz_path: Path,
    splits: Optional[list[str]] = None,
) -> None:
    """
    Merge original and synthetic NPZ files.

    Args:
        original_npz_path: Path to original dataset NPZ file
        synth_npz_path: Path to synthetic dataset NPZ file
        output_npz_path: Path where to save merged NPZ file
        splits: List of splits to merge (default: ["train", "val", "test"])

    Raises:
        FileNotFoundError: If input files don't exist
        ValueError: If no valid splits are found
    """
    if not original_npz_path.exists():
        raise FileNotFoundError(f"Original NPZ file not found: {original_npz_path}")

    if not synth_npz_path.exists():
        raise FileNotFoundError(f"Synthetic NPZ file not found: {synth_npz_path}")

    if splits is None:
        splits = ["train", "val", "test"]

    logger.info("=" * 80)
    logger.info("Merging NPZ files")
    logger.info("=" * 80)
    logger.info(f"Original: {original_npz_path}")
    logger.info(f"Synthetic: {synth_npz_path}")
    logger.info(f"Output: {output_npz_path}")
    logger.info(f"Splits to merge: {splits}")
    logger.info("=" * 80)

    # Load NPZ files
    logger.info("Loading NPZ files...")
    original_data = np.load(original_npz_path)
    synth_data = np.load(synth_npz_path)

    logger.info(f"Original NPZ keys: {list(original_data.keys())}")
    logger.info(f"Synthetic NPZ keys: {list(synth_data.keys())}")

    # Merge each split
    merged_data = {}

    for split_name in splits:
        split_merged = merge_split(original_data, synth_data, split_name)
        if split_merged:
            merged_data.update(split_merged)

    if not merged_data:
        raise ValueError("No valid splits were merged. Check your input files and split names.")

    # Save merged NPZ
    logger.info(f"\nSaving merged NPZ to {output_npz_path}...")
    output_npz_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(str(output_npz_path), **merged_data)

    # Verify saved file
    logger.info("Verifying saved file...")
    verification = np.load(output_npz_path)
    logger.info(f"Saved NPZ keys: {list(verification.keys())}")

    for key in sorted(verification.keys()):
        logger.info(f"  {key}: shape={verification[key].shape}, dtype={verification[key].dtype}")

    logger.info("=" * 80)
    logger.info("Merge completed successfully!")
    logger.info("=" * 80)


def main() -> None:
    """
    Entry point for the merge utility script.
    """
    parser = argparse.ArgumentParser(
        description="Merge synthetic images with original dataset in NPZ format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Merge all splits (train, val, test)
  python -m medsyn.utils.merge_synth_with_original \\
    --original /path/to/original.npz \\
    --synthetic /path/to/synthetic.npz \\
    --output /path/to/merged.npz

  # Merge only train and val splits
  python -m medsyn.utils.merge_synth_with_original \\
    --original /path/to/original.npz \\
    --synthetic /path/to/synthetic.npz \\
    --output /path/to/merged.npz \\
    --splits train val

  # Using short argument names
  python -m medsyn.utils.merge_synth_with_original \\
    -o /path/to/original.npz \\
    -s /path/to/synthetic.npz \\
    -t /path/to/merged.npz

Input NPZ files should have the following structure:
  {split}_images: [N, H, W, C] uint8
  {split}_labels: [N] int64
  {split}_is_synth: [N] bool

The output NPZ will have the same structure with combined samples.
You can distinguish real from synthetic using the is_synth flag.
        """,
    )

    parser.add_argument(
        "-o",
        "--original",
        type=str,
        required=True,
        help="Path to original dataset NPZ file",
    )

    parser.add_argument(
        "-s",
        "--synthetic",
        type=str,
        required=True,
        help="Path to synthetic dataset NPZ file",
    )

    parser.add_argument(
        "-t",
        "--output",
        type=str,
        required=True,
        help="Path where to save merged NPZ file",
    )

    parser.add_argument(
        "--splits",
        type=str,
        nargs="+",
        default=None,
        help="Splits to merge (default: train val test). Example: --splits train val",
    )

    args = parser.parse_args()

    # Convert paths
    original_path = Path(args.original).expanduser().resolve()
    synth_path = Path(args.synthetic).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    try:
        merge_npz_files(
            original_npz_path=original_path,
            synth_npz_path=synth_path,
            output_npz_path=output_path,
            splits=args.splits,
        )
    except Exception as e:
        logger.error("Merge failed: %s", e, exc_info=True)
        raise SystemExit(1) from e


if __name__ == "__main__":
    main()
