#!/usr/bin/env python3
"""
medsyn/utils/merge_synth_with_original.py

Utility script to merge synthetic images (generated by ccDDPM) with original dataset.

The script combines NPZ files containing:
- Original dataset: Single NPZ file with all splits: {split}_images, {split}_labels, {split}_is_synth (all False)
- Synthetic dataset: Multiple NPZ files organized by split directories:
  - <base_dir>/train/<dataset>_train_synth.npz
  - <base_dir>/val/<dataset>_val_synth.npz
  - <base_dir>/test/<dataset>_test_synth.npz

Output format maintains the same structure with both real and synthetic samples.
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Optional

import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s - %(name)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def merge_split(
    original_data: dict[str, np.ndarray],
    synth_data: dict[str, np.ndarray],
    split_name: str,
) -> dict[str, np.ndarray]:
    """
    Merge original and synthetic data for a single split.

    Args:
        original_data: Dictionary from original NPZ file
        synth_data: Dictionary from synthetic NPZ file
        split_name: Name of the split (train, val, test)

    Returns:
        Dictionary with merged data for this split

    Raises:
        KeyError: If required keys are missing
        ValueError: If array shapes are incompatible
    """
    logger.info(f"Merging {split_name} split...")

    # Keys for this split
    images_key = f"{split_name}_images"
    labels_key = f"{split_name}_labels"
    is_synth_key = f"{split_name}_is_synth"

    # Check if split exists in both datasets
    if images_key not in original_data:
        logger.warning(f"Split '{split_name}' not found in original dataset, skipping...")
        return {}

    if images_key not in synth_data:
        logger.warning(f"Split '{split_name}' not found in synthetic dataset, skipping...")
        return {}

    # Load original data
    orig_images = original_data[images_key]
    orig_labels = original_data[labels_key]
    orig_is_synth = original_data.get(is_synth_key, np.zeros(len(orig_images), dtype=bool))

    # Load synthetic data
    synth_images = synth_data[images_key]
    synth_labels = synth_data[labels_key]
    synth_is_synth = synth_data.get(is_synth_key, np.ones(len(synth_images), dtype=bool))

    # Validate shapes
    if orig_images.shape[1:] != synth_images.shape[1:]:
        raise ValueError(
            f"Image shape mismatch for {split_name}: "
            f"original {orig_images.shape[1:]} vs synthetic {synth_images.shape[1:]}"
        )

    logger.info(f"  Original: {len(orig_images)} samples (is_synth: {orig_is_synth.sum()} True)")
    logger.info(f"  Synthetic: {len(synth_images)} samples (is_synth: {synth_is_synth.sum()} True)")

    # Concatenate arrays
    merged_images = np.concatenate([orig_images, synth_images], axis=0)
    merged_labels = np.concatenate([orig_labels, synth_labels], axis=0)
    merged_is_synth = np.concatenate([orig_is_synth, synth_is_synth], axis=0)

    logger.info(f"  Merged: {len(merged_images)} samples total")
    logger.info(f"    Real: {(~merged_is_synth).sum()} samples")
    logger.info(f"    Synthetic: {merged_is_synth.sum()} samples")

    # Verify data types
    if merged_images.dtype != np.uint8:
        logger.warning(f"Converting images from {merged_images.dtype} to uint8")
        merged_images = merged_images.astype(np.uint8)

    if merged_labels.dtype != np.int64:
        logger.warning(f"Converting labels from {merged_labels.dtype} to int64")
        merged_labels = merged_labels.astype(np.int64)

    return {
        images_key: merged_images,
        labels_key: merged_labels,
        is_synth_key: merged_is_synth,
    }


def merge_npz_files(
    original_npz_path: Path,
    synth_base_path: Path,
    output_npz_path: Path,
    splits: Optional[list[str]] = None,
    dataset_name: str = "pathmnist",
) -> None:
    """
    Merge original and synthetic NPZ files.

    Args:
        original_npz_path: Path to original dataset NPZ file (contains all splits)
        synth_base_path: Path to base directory containing split subdirectories
                        (e.g., /path/to/generated/ containing train/, val/, test/)
        output_npz_path: Path where to save merged NPZ file
        splits: List of splits to merge (default: ["train", "val", "test"])
        dataset_name: Dataset name used in NPZ filenames (default: "pathmnist")

    Raises:
        FileNotFoundError: If input files don't exist
        ValueError: If no valid splits are found
    """
    if not original_npz_path.exists():
        raise FileNotFoundError(f"Original NPZ file not found: {original_npz_path}")

    if not synth_base_path.exists():
        raise FileNotFoundError(f"Synthetic base directory not found: {synth_base_path}")

    if not synth_base_path.is_dir():
        raise ValueError(f"Synthetic base path must be a directory: {synth_base_path}")

    if splits is None:
        splits = ["train", "val", "test"]

    logger.info("=" * 80)
    logger.info("Merging NPZ files")
    logger.info("=" * 80)
    logger.info(f"Original: {original_npz_path}")
    logger.info(f"Synthetic base directory: {synth_base_path}")
    logger.info(f"Output: {output_npz_path}")
    logger.info(f"Splits to merge: {splits}")
    logger.info(f"Dataset name: {dataset_name}")
    logger.info("=" * 80)

    # Load original NPZ file (contains all splits)
    logger.info("Loading original NPZ file...")
    original_data = np.load(original_npz_path)
    logger.info(f"Original NPZ keys: {list(original_data.keys())}")

    # Merge each split
    merged_data = {}

    for split_name in splits:
        # Construct path to synthetic NPZ for this split
        synth_split_dir = synth_base_path / split_name
        synth_npz_filename = f"{dataset_name}_{split_name}_synth.npz"
        synth_npz_path = synth_split_dir / synth_npz_filename

        if not synth_npz_path.exists():
            logger.warning(f"Synthetic NPZ not found for split '{split_name}': {synth_npz_path}")
            logger.warning(f"Skipping split '{split_name}'...")
            continue

        # Load synthetic NPZ for this split
        logger.info(f"\nLoading synthetic NPZ for split '{split_name}': {synth_npz_path}")
        synth_data = np.load(synth_npz_path)
        logger.info(f"Synthetic NPZ keys: {list(synth_data.keys())}")

        # Merge this split
        split_merged = merge_split(original_data, synth_data, split_name)
        if split_merged:
            merged_data.update(split_merged)

    if not merged_data:
        raise ValueError("No valid splits were merged. Check your input files and split names.")

    # Save merged NPZ
    logger.info(f"\nSaving merged NPZ to {output_npz_path}...")
    output_npz_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(str(output_npz_path), **merged_data)

    # Verify saved file
    logger.info("Verifying saved file...")
    verification = np.load(output_npz_path)
    logger.info(f"Saved NPZ keys: {list(verification.keys())}")

    for key in sorted(verification.keys()):
        logger.info(f"  {key}: shape={verification[key].shape}, dtype={verification[key].dtype}")

    logger.info("=" * 80)
    logger.info("Merge completed successfully!")
    logger.info("=" * 80)


def sanity_check_merged_npz(
    original_npz_path: Path,
    synth_base_path: Path,
    merged_npz_path: Path,
    splits: Optional[list[str]] = None,
    dataset_name: str = "pathmnist",
) -> bool:
    """
    Perform sanity checks on the merged NPZ file.

    Verifies that:
    1. All expected keys are present in the merged file
    2. Sample counts match (original + synthetic = merged)
    3. Data types are correct
    4. is_synth flags are correctly set
    5. No data corruption occurred
    6. Image and label shapes are consistent

    Args:
        original_npz_path: Path to original dataset NPZ file
        synth_base_path: Path to base directory containing split subdirectories
        merged_npz_path: Path to merged NPZ file
        splits: List of splits to check (default: ["train", "val", "test"])
        dataset_name: Dataset name used in NPZ filenames (default: "pathmnist")

    Returns:
        True if all checks pass, False otherwise

    Raises:
        FileNotFoundError: If any required file doesn't exist
    """
    if splits is None:
        splits = ["train", "val", "test"]

    logger.info("=" * 80)
    logger.info("SANITY CHECK: Verifying merged NPZ file")
    logger.info("=" * 80)

    all_checks_passed = True

    try:
        # Load all files
        logger.info("Loading NPZ files for verification...")
        original_data = np.load(original_npz_path)
        merged_data = np.load(merged_npz_path)

        logger.info(f"Original NPZ keys: {list(original_data.keys())}")
        logger.info(f"Merged NPZ keys: {list(merged_data.keys())}")

        # Check each split
        for split_name in splits:
            logger.info(f"\n{'=' * 60}")
            logger.info(f"Checking split: {split_name}")
            logger.info(f"{'=' * 60}")

            images_key = f"{split_name}_images"
            labels_key = f"{split_name}_labels"
            is_synth_key = f"{split_name}_is_synth"

            # Check if split exists in original
            if images_key not in original_data:
                logger.warning(f"Split '{split_name}' not found in original dataset, skipping checks...")
                continue

            # Check if synthetic NPZ exists for this split
            synth_split_dir = synth_base_path / split_name
            synth_npz_filename = f"{dataset_name}_{split_name}_synth.npz"
            synth_npz_path = synth_split_dir / synth_npz_filename

            if not synth_npz_path.exists():
                logger.warning(f"Synthetic NPZ not found for split '{split_name}', skipping checks...")
                continue

            synth_data = np.load(synth_npz_path)

            # Check 1: Verify all required keys exist in merged file
            logger.info("\n[Check 1] Verifying required keys exist in merged file...")
            required_keys = [images_key, labels_key, is_synth_key]
            for key in required_keys:
                if key not in merged_data:
                    logger.error(f"  ✗ Missing key '{key}' in merged NPZ!")
                    all_checks_passed = False
                else:
                    logger.info(f"  ✓ Key '{key}' present")

            if not all([key in merged_data for key in required_keys]):
                logger.error(f"Skipping remaining checks for split '{split_name}' due to missing keys")
                continue

            # Get data arrays
            orig_images = original_data[images_key]
            orig_labels = original_data[labels_key]
            orig_is_synth = original_data.get(is_synth_key, np.zeros(len(orig_images), dtype=bool))

            synth_images = synth_data[images_key]
            synth_labels = synth_data[labels_key]
            synth_is_synth = synth_data.get(is_synth_key, np.ones(len(synth_images), dtype=bool))

            merged_images = merged_data[images_key]
            merged_labels = merged_data[labels_key]
            merged_is_synth = merged_data[is_synth_key]

            # Check 2: Sample count verification
            logger.info("\n[Check 2] Verifying sample counts...")
            orig_count = len(orig_images)
            synth_count = len(synth_images)
            merged_count = len(merged_images)
            expected_count = orig_count + synth_count

            logger.info(f"  Original samples: {orig_count}")
            logger.info(f"  Synthetic samples: {synth_count}")
            logger.info(f"  Merged samples: {merged_count}")
            logger.info(f"  Expected merged: {expected_count}")

            if merged_count == expected_count:
                logger.info(f"  ✓ Sample count matches: {merged_count} == {expected_count}")
            else:
                logger.error(f"  ✗ Sample count mismatch: {merged_count} != {expected_count}")
                all_checks_passed = False

            # Check 3: Data type verification
            logger.info("\n[Check 3] Verifying data types...")
            checks = [
                (merged_images.dtype == np.uint8, f"Images dtype is uint8: {merged_images.dtype}"),
                (merged_labels.dtype == np.int64, f"Labels dtype is int64: {merged_labels.dtype}"),
                (merged_is_synth.dtype == bool, f"is_synth dtype is bool: {merged_is_synth.dtype}"),
            ]

            for check_passed, msg in checks:
                if check_passed:
                    logger.info(f"  ✓ {msg}")
                else:
                    logger.error(f"  ✗ {msg}")
                    all_checks_passed = False

            # Check 4: Shape verification
            logger.info("\n[Check 4] Verifying array shapes...")
            if len(merged_images) == len(merged_labels) == len(merged_is_synth):
                logger.info(f"  ✓ All arrays have same length: {len(merged_images)}")
            else:
                logger.error(f"  ✗ Array length mismatch:")
                logger.error(f"    Images: {len(merged_images)}")
                logger.error(f"    Labels: {len(merged_labels)}")
                logger.error(f"    is_synth: {len(merged_is_synth)}")
                all_checks_passed = False

            # Check image dimensions match
            if orig_images.shape[1:] == synth_images.shape[1:] == merged_images.shape[1:]:
                logger.info(f"  ✓ Image dimensions consistent: {merged_images.shape[1:]}")
            else:
                logger.error(f"  ✗ Image dimension mismatch:")
                logger.error(f"    Original: {orig_images.shape[1:]}")
                logger.error(f"    Synthetic: {synth_images.shape[1:]}")
                logger.error(f"    Merged: {merged_images.shape[1:]}")
                all_checks_passed = False

            # Check 5: is_synth flag verification
            logger.info("\n[Check 5] Verifying is_synth flags...")
            num_real = (~merged_is_synth).sum()
            num_synth = merged_is_synth.sum()

            logger.info(f"  Real samples (is_synth=False): {num_real}")
            logger.info(f"  Synthetic samples (is_synth=True): {num_synth}")

            if num_real == orig_count:
                logger.info(f"  ✓ Real sample count matches original: {num_real} == {orig_count}")
            else:
                logger.error(f"  ✗ Real sample count mismatch: {num_real} != {orig_count}")
                all_checks_passed = False

            if num_synth == synth_count:
                logger.info(f"  ✓ Synthetic sample count matches: {num_synth} == {synth_count}")
            else:
                logger.error(f"  ✗ Synthetic sample count mismatch: {num_synth} != {synth_count}")
                all_checks_passed = False

            # Check 6: Label distribution verification
            logger.info("\n[Check 6] Verifying label distributions...")
            
            # Check original labels are preserved
            orig_unique_labels = np.unique(orig_labels)
            merged_real_labels = merged_labels[~merged_is_synth]
            
            if len(merged_real_labels) == len(orig_labels):
                logger.info(f"  ✓ Original labels count preserved: {len(merged_real_labels)}")
            else:
                logger.error(f"  ✗ Original labels count mismatch: {len(merged_real_labels)} != {len(orig_labels)}")
                all_checks_passed = False

            # Check synthetic labels are preserved
            synth_unique_labels = np.unique(synth_labels)
            merged_synth_labels = merged_labels[merged_is_synth]
            
            if len(merged_synth_labels) == len(synth_labels):
                logger.info(f"  ✓ Synthetic labels count preserved: {len(merged_synth_labels)}")
            else:
                logger.error(f"  ✗ Synthetic labels count mismatch: {len(merged_synth_labels)} != {len(synth_labels)}")
                all_checks_passed = False

            logger.info(f"  Original label classes: {sorted(orig_unique_labels.tolist())}")
            logger.info(f"  Synthetic label classes: {sorted(synth_unique_labels.tolist())}")
            logger.info(f"  Merged label classes: {sorted(np.unique(merged_labels).tolist())}")

            # Check 7: Data integrity spot check (compare first and last samples)
            logger.info("\n[Check 7] Data integrity spot check...")
            
            # First real sample should match first original sample
            if np.array_equal(merged_images[0], orig_images[0]):
                logger.info(f"  ✓ First real image matches original")
            else:
                logger.error(f"  ✗ First real image differs from original!")
                all_checks_passed = False

            if merged_labels[0] == orig_labels[0]:
                logger.info(f"  ✓ First real label matches original: {merged_labels[0]}")
            else:
                logger.error(f"  ✗ First real label differs: {merged_labels[0]} != {orig_labels[0]}")
                all_checks_passed = False

            # First synthetic sample should match first synthetic sample
            first_synth_idx = np.where(merged_is_synth)[0][0] if merged_is_synth.any() else -1
            if first_synth_idx >= 0:
                if np.array_equal(merged_images[first_synth_idx], synth_images[0]):
                    logger.info(f"  ✓ First synthetic image matches source")
                else:
                    logger.error(f"  ✗ First synthetic image differs from source!")
                    all_checks_passed = False

                if merged_labels[first_synth_idx] == synth_labels[0]:
                    logger.info(f"  ✓ First synthetic label matches source: {merged_labels[first_synth_idx]}")
                else:
                    logger.error(f"  ✗ First synthetic label differs: {merged_labels[first_synth_idx]} != {synth_labels[0]}")
                    all_checks_passed = False

        logger.info("\n" + "=" * 80)
        if all_checks_passed:
            logger.info("✓ ALL SANITY CHECKS PASSED!")
            logger.info("The merged NPZ file appears to be correctly constructed.")
        else:
            logger.error("✗ SOME SANITY CHECKS FAILED!")
            logger.error("Please review the errors above and verify your data.")
        logger.info("=" * 80)

        return all_checks_passed

    except Exception as e:
        logger.error(f"Sanity check failed with exception: {e}", exc_info=True)
        return False


def main() -> None:
    """
    Entry point for the merge utility script.
    """
    parser = argparse.ArgumentParser(
        description="Merge synthetic images with original dataset in NPZ format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Merge all splits (train, val, test)
  python -m medsyn.utils.merge_synth_with_original \\
    --original /path/to/original.npz \\
    --synthetic /path/to/generated_base_dir \\
    --output /path/to/merged.npz

  # Merge with automatic sanity check
  python -m medsyn.utils.merge_synth_with_original \\
    --original /path/to/original.npz \\
    --synthetic /path/to/generated_base_dir \\
    --output /path/to/merged.npz \\
    --sanity-check

  # Run sanity check only on existing merged file
  python -m medsyn.utils.merge_synth_with_original \\
    --original /path/to/original.npz \\
    --synthetic /path/to/generated_base_dir \\
    --output /path/to/merged.npz \\
    --sanity-check-only

  # Merge only train and val splits
  python -m medsyn.utils.merge_synth_with_original \\
    --original /path/to/original.npz \\
    --synthetic /path/to/generated_base_dir \\
    --output /path/to/merged.npz \\
    --splits train val

  # Using short argument names with custom dataset name
  python -m medsyn.utils.merge_synth_with_original \\
    -o /path/to/original.npz \\
    -s /path/to/generated_base_dir \\
    -t /path/to/merged.npz \\
    --dataset-name pathmnist

Directory structure expected for synthetic data:
  <synthetic_base_dir>/
    train/
      pathmnist_train_synth.npz
      class_0/, class_1/, ...
    val/
      pathmnist_val_synth.npz
      class_0/, class_1/, ...
    test/
      pathmnist_test_synth.npz
      class_0/, class_1/, ...

Input NPZ files should have the following structure:
  {split}_images: [N, H, W, C] uint8
  {split}_labels: [N] int64
  {split}_is_synth: [N] bool

The output NPZ will have the same structure with combined samples.
You can distinguish real from synthetic using the is_synth flag.

Sanity check verifies:
  - Correct sample counts (original + synthetic = merged)
  - Proper data types (uint8, int64, bool)
  - Array shape consistency
  - is_synth flags correctly set
  - Data integrity (spot checks on samples)
  - Label distributions preserved
        """,
    )

    parser.add_argument(
        "-o",
        "--original",
        type=str,
        required=True,
        help="Path to original dataset NPZ file (contains all splits)",
    )

    parser.add_argument(
        "-s",
        "--synthetic",
        type=str,
        required=True,
        help="Path to synthetic dataset base directory (contains train/, val/, test/ subdirectories)",
    )

    parser.add_argument(
        "-t",
        "--output",
        type=str,
        required=True,
        help="Path where to save merged NPZ file",
    )

    parser.add_argument(
        "--splits",
        type=str,
        nargs="+",
        default=None,
        help="Splits to merge (default: train val test). Example: --splits train val",
    )

    parser.add_argument(
        "--dataset-name",
        type=str,
        default="pathmnist",
        help="Dataset name used in synthetic NPZ filenames (default: pathmnist)",
    )

    parser.add_argument(
        "--sanity-check",
        action="store_true",
        help="Run sanity checks on the merged NPZ file after creation",
    )

    parser.add_argument(
        "--sanity-check-only",
        action="store_true",
        help="Only run sanity checks on an existing merged NPZ file (skip merging)",
    )

    args = parser.parse_args()

    # Convert paths
    original_path = Path(args.original).expanduser().resolve()
    synth_base_path = Path(args.synthetic).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    try:
        # Sanity check only mode
        if args.sanity_check_only:
            logger.info("Running sanity check only (no merging)...")
            if not output_path.exists():
                logger.error(f"Merged NPZ file not found: {output_path}")
                logger.error("Cannot run sanity check. Please merge the files first.")
                sys.exit(1)

            checks_passed = sanity_check_merged_npz(
                original_npz_path=original_path,
                synth_base_path=synth_base_path,
                merged_npz_path=output_path,
                splits=args.splits,
                dataset_name=args.dataset_name,
            )

            sys.exit(0 if checks_passed else 1)

        # Normal merge operation
        merge_npz_files(
            original_npz_path=original_path,
            synth_base_path=synth_base_path,
            output_npz_path=output_path,
            splits=args.splits,
            dataset_name=args.dataset_name,
        )

        # Run sanity check if requested
        if args.sanity_check:
            logger.info("\n" + "=" * 80)
            logger.info("Running post-merge sanity checks...")
            logger.info("=" * 80 + "\n")

            checks_passed = sanity_check_merged_npz(
                original_npz_path=original_path,
                synth_base_path=synth_base_path,
                merged_npz_path=output_path,
                splits=args.splits,
                dataset_name=args.dataset_name,
            )

            if not checks_passed:
                logger.warning("\n⚠ WARNING: Some sanity checks failed. Please review the output above.")
                sys.exit(1)

    except Exception as e:
        logger.error("Merge failed: %s", e, exc_info=True)
        raise SystemExit(1) from e


if __name__ == "__main__":
    main()
