data:
  flag: pathmnist
  size: 28
  download_dir: /home/mpascual/research/datasets/medsyn/PathMNIST/data_raw         # guarda pathmnist.npz
  processed_dir: /home/mpascual/research/datasets/medsyn/PathMNIST/data_processed  # almacena PNGs por split
  index_json: /home/mpascual/research/datasets/medsyn/PathMNIST/indexes/pathmnist_index.json
  seed: 23102003
  num_workers: 4
  reduction:
    strategy: fraction
    train: 0.20
    val: 1.00
    test: 1.00
    max_per_class: null

bVAE:
  model:
    in_channels: 3
    img_size: 28
    latent_dim: 16
    base_channels: 32
    num_down: 3
    decoder_sigmoid: true
  train:
    epochs: 50
    batch_size: 128
    num_workers: 4
    device: cuda
    mixed_precision: true
    grad_clip_norm: 1.0
    seed: 17
    output_dir: ./outputs/bvae_pathmnist
  optim:
    optimizer: adamw
    lr_init: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-8
  sched:
    use_onecycle: true
    max_lr: 3.0e-4
    pct_start: 0.3
    div_factor: 25.0
    final_div_factor: 10000.0
  loss:
    beta: 2.0
    recon_type: mse         # or: bce
    recon_weight: 1.0
    kld_weight: 1.0
